# Setup Pageant to auto-load key with passphrase
# This creates a startup script and adds it to Windows startup

$ErrorActionPreference = "Continue"

Write-Host "`n🔧 Setting up Pageant Auto-Load..." -ForegroundColor Cyan

# Pageant path
$pageantPath = "C:\Program Files\PuTTY\pageant.exe"

if (-not (Test-Path $pageantPath)) {
    Write-Host "`n❌ Pageant not found. Please install PuTTY." -ForegroundColor Red
    exit 1
}

# Load config
$configPath = "cpanel-config.json"
if (-not (Test-Path $configPath)) {
    Write-Host "`n❌ Config file not found: $configPath" -ForegroundColor Red
    exit 1
}

$config = Get-Content $configPath | ConvertFrom-Json
$keyPath = $config.ssh.keyPath
$passphrase = $config.ssh.password

# Create a startup script
$startupScript = @"
# Auto-load SSH key into Pageant on startup
# Generated by setup_pageant_auto.ps1

`$pageantPath = "$pageantPath"
`$keyPath = "$keyPath"
`$passphrase = "$passphrase"

# Start Pageant if not running
`$pageant = Get-Process -Name "pageant" -ErrorAction SilentlyContinue
if (-not `$pageant) {
    Start-Process -FilePath `$pageantPath -WindowStyle Minimized
    Start-Sleep -Seconds 2
}

# Load key (will prompt for passphrase first time)
Start-Process -FilePath `$pageantPath -ArgumentList "`"`$keyPath`"" -WindowStyle Minimized
"@

$scriptPath = "$env:USERPROFILE\Documents\load_pageant.ps1"
$startupScript | Out-File -FilePath $scriptPath -Encoding UTF8

Write-Host "`n✅ Created startup script: $scriptPath" -ForegroundColor Green

# Create a batch file for Task Scheduler
$batchContent = @"
@echo off
powershell.exe -ExecutionPolicy Bypass -File "$scriptPath"
"@

$batchPath = "$env:USERPROFILE\Documents\load_pageant.bat"
$batchContent | Out-File -FilePath $batchPath -Encoding ASCII

Write-Host "✅ Created batch file: $batchPath" -ForegroundColor Green

# Add to Windows startup (User folder)
$startupFolder = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup"
$startupLink = "$startupFolder\Load Pageant.lnk"

try {
    $WshShell = New-Object -ComObject WScript.Shell
    $Shortcut = $WshShell.CreateShortcut($startupLink)
    $Shortcut.TargetPath = $batchPath
    $Shortcut.WorkingDirectory = Split-Path $batchPath
    $Shortcut.WindowStyle = 1  # Minimized
    $Shortcut.Save()
    Write-Host "✅ Added to Windows Startup folder" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Could not add to startup automatically" -ForegroundColor Yellow
    Write-Host "   Manually add: $batchPath to Startup folder" -ForegroundColor Gray
}

# Load key now
Write-Host "`n🚀 Loading key into Pageant now..." -ForegroundColor Cyan
& $scriptPath

Write-Host "`n✅ Setup complete!" -ForegroundColor Green
Write-Host "`n💡 Pageant will now load your key on Windows startup." -ForegroundColor Cyan
Write-Host "   Passphrase: $passphrase" -ForegroundColor Gray
Write-Host "   (You may need to enter it once per session)" -ForegroundColor Gray

